<div class="alert alert-warning alert-dismissible fade show flash" id="flash" role="alert">
    <strong>Holy guacamole!</strong> You should check in on some of those fields below.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<script>
    setTimeout(function(){
        document.getElementById('flash').style.display = 'none';
    }, 5000);
</script>