<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $this->title ?></title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
            integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
            crossorigin="anonymous"></script>
</head>
<body onLoad="window.print()">
<div class="col d-flex flex-column h-sm-100">

                    <table class="table table-borderless table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Anzahl</th>
                            <th scope="col">Gebinde</th>
                            <th scope="col">Artikel</th>
                            <th scope="col">Kategorie</th>
                            <th scope="col">Shop</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->__get('article') as $article) { ?>
                            <tr>
                                <th scope="row"><?= $article->getAnzahl() ?></th>
                                <td>
                                    <?= $article->getBundle() ?>
                                </td>
                                <td>
                                    <?= $article->getName() ?>
                                </td>
                                <td>
                                    <?= $article->getCat() ?>
                                </td>
                                <td>
                                    <?= $article->getShop() ?>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>
            <button class="btn btn-primary graybutton" onclick="window.location.href='https://<?= URL ?>';">
                Zurück
            </button>

</div>
</body>