<?php
$shop = $this->__get('shop');
$this->renderPart('Header');
$this->renderPart('Navigation');
$cats = $this->__get('catsort');
?>
    <div class="col d-flex flex-column h-sm-100">
        <div class="content">

            <div class="col-12 box">
                <div class="boxheader">Shop bearbeiten</div>
                <div class="boxbody">


                    <form class="row g-3" action="https://<?= URL ?>shop/setting/edit/<?= $shop[0]->getId() ?>"
                          method="POST">

                        <div class="col-md-6">
                            <label for="inputCity" class="form-label">Reihenfolge der Kategorien festlegen</label>
                            <input type="text" class="form-control" id="inputCity" name="shop"
                                   value="<?= $shop[0]->getName() ?>">
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-primary graybutton">Bearbeiten</button>
                        </div>
                    </form>

                </div>
                <div class="boxfooter"></div>
            </div>
            <div class="col-12 box">
                <div class="boxheader">Reihenfolge der Kategorien festlegen</div>
                <div class="boxbody">


                    <form class="row g-12" action="https://<?= URL ?>shop/settings/cat/<?= $shop[0]->getId() ?>"
                          method="POST">


                        <table class="table table-borderless table_main">
                            <thead>
                            <tr>
                                <th scope="col">Kategorie</th>
                                <th scope="col">Position</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($cats as $cat) { ?>
                                <tr>
                                    <th scope="row"><?= $cat->getName() ?></th>
                                    <td>
                                        <input type="hidden" name="catID[]" value="<?= $cat->getId() ?>">
                                        <input type="text" class="form-control" id="inputCity" name="postion[]" size="1"
                                               value="<?= $cat->getPosition() ?>">
                                    </td>
                                </tr>
                            <?php } ?>

                            </tbody>


                        </table>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary graybutton">Bearbeiten</button>
                        </div>
                    </form>

                </div>
                <div class="boxfooter"></div>
            </div>

<?php
$this->displayMSG();
?>


    </div>

    </div>
<?php
$this->renderPart('Footer');
