<?php
$this->renderPart('Header');
$this->renderPart('Navigation');
?>
    <div class="col d-flex flex-column h-sm-100">
        <div class="content">
            <div class="col-12 box">
                <div class="boxheader">Alle Kategorien</div>
                <div class="boxbody">

                    <table class="table table-borderless table_main">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Aktion</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->__get('cat') as $cat) { ?>
                            <tr>
                                <th scope="row"><?= $cat->getName() ?></th>
                                <td><i class="fas fa-pen" aria-hidden="true"></i>&nbsp; &nbsp;&nbsp; &nbsp;<i
                                            class="fas fa-trash"></i><?= $cat->getId() ?>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>


                </div>
                <div class="boxfooter"></div>
            </div>


            <div class="col-12 box">
                <div class="boxheader">Neue Kategorie anlegen</div>
                <div class="boxbody">


                    <form class="row g-3">

                        <div class="col-md-6">
                            <label for="inputCity" class="form-label">Name der Kategorie</label>
                            <input type="text" class="form-control" id="inputCity">
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-primary graybutton">Anlegen</button>
                        </div>
                    </form>

                </div>
                <div class="boxfooter"></div>
            </div>
            <?php
            $this->displayMSG();
            ?>


        </div>

    </div>

    </div>

<?php
$this->renderPart('Footer');
